fix broken links, content and update image
tigergraph/server-docs pull request #2
Opened 2021-12-03 20:19 UTC by lennessyy

2021-12-03 23:01 UTC, kevinliu24 requested changes

2021-12-03 23:01 UTC, kevinliu24 commented on modules/installation/pages/upgrade.adoc
> +[[upgrading-cloud-marketplace-image]]
Also need to add instructions for upgrading from previous 3.x edition of marketplace images. All that needs to be done is use GBar to backup the old instance and restore it on the new one.
1. Backup old marketplace instance using gbar backup.
2. Start an instance with the latest Cloud Marketplace listing
3. Restore the old backup on to the new listing
You may also want to add a reference to the Gbar documentation for more information.

2021-12-04 00:06 UTC, lennessyy commented
@kevinliu24 Thanks for the comment - I've added the instructions for 3.x

2021-12-04 00:20 UTC, kevinliu24 approved these changes
LGTM

2021-12-04 00:49 UTC, merged