CPU usage based query routing
tigergraph/server-docs pull request #341
Opened 2023-10-12 17:18 UTC by JosephNewmanTG

Associated Task: https://graphsql.atlassian.net/browse/DOC-1828

- Added enable instructions on workload management
- Added config commands configure parameters table

2023-10-13 13:23 UTC, victorleeTG requested changes
I ended up proposing a rewrite of all the information. It wasn't bad or wrong; I just wanted it to be better.  Happy to walk through this with you.

This comes out from stepping back and seeing how would you present all of the options to a new user, and to make sure users on different versions know what is/isn't available to them.


Also, as we discussed before, in the future, do not combine unrelated changes into the same PR.  The goal is each "feature" = 1 DOC ticket = 1 PR.

2023-10-13 13:23 UTC, victorleeTG commented on modules/system-management/pages/workload-management.adoc
> +== Replica/Partition routing based on CPU Usage
This new feature is thematically related to an existing feature "Specify Replica to Run Query On" and so should be presented in connection with it.  I would present Query Routing Schemas (round-robin and CPU load aware) first, and then Specify Replica (with the GSQL-REPLICA header) next.

Reason: Round-Robin is the default mode and so should come first. CPU Load Aware is an alternative to Round-Robin. The GSQL-Replica header is an override of any of these modes.

2023-10-13 13:23 UTC, victorleeTG commented on modules/system-management/pages/workload-management.adoc
> +== Replica/Partition routing based on CPU Usage
```suggestion
== Query Routing Schemes
```

2023-10-13 13:23 UTC, victorleeTG commented on modules/system-management/pages/workload-management.adoc
> +This is so that queries don’t overwhelm nodes that are already under a heavy load.
```suggestion
In a distributed or replicated cluster, REST++ automatically routes queries to different GPEs, in order to spread the workload.

NOTE: If GSQL-REPLICA header is used when invoking a query, this header overrides the routing schema for that query.

=== Round Robin routing
 The default query routing scheme is round-robin. The first query is managed by GPE 0, the next query by GPE 1, and so on. After the last GPE, the cycle returns to GPE 0.
 
```

2023-10-13 13:23 UTC, victorleeTG commented on modules/system-management/pages/workload-management.adoc
> +NOTE: Query routing mode has two options: 0=RoundRobin and 1=CPULoadAware.
```suggestion
Version 3.9.3 adds a system configuration parameter `RESTPP.CPULoadAware.Mode` to enable system administrators to select other query routing schemas:

* Mode = 0 (default): Round-Robin
* Mode = 1: CPU Load Aware 

=== CPU Load Aware Query Routing
When enabled, REST++ tries to direct incoming queries to the GPEs that are currently less busy.
Specifically, the system periodically polls CPU usage data to find a GPE whose CPU usage percentage is below `RESTPP.QueryRouting.TargetSelectionCPUThreshold` (default 50).

If no GPE satisfies the CPU threshold condition, REST++ falls back to the default behavior (round-robin selection).

```

2023-10-13 13:23 UTC, victorleeTG commented on modules/system-management/pages/workload-management.adoc
> +NOTE: Query routing mode has two options: 0=RoundRobin and 1=CPULoadAware.
Avoid using NOTEs to highlight basic facts. Instead, organize and phrase your presentation so that the reader will naturally notice the basic facts.

2023-10-13 13:23 UTC, victorleeTG commented on modules/system-management/pages/workload-management.adoc
> +This is so that queries don’t overwhelm nodes that are already under a heavy load.
Remember to point out when a feature is only available starting from 3.9.3. Please double check your other doc tickets.

2023-10-13 13:23 UTC, victorleeTG commented on modules/system-management/pages/workload-management.adoc
> +NOTE: Default CPU threshold is set at 50.
```suggestion
.Example: Change CPU Load Threshold and Enable CPU Load Aware routing
[source, console]
$ gadmin config entry RESTPP.QueryRouting.TargetSelectionCPUThreshold 40
$ gadmin config entry RESTPP.QueryRouting.Mode 1
```

2023-10-14 01:01 UTC, JosephNewmanTG commented on modules/system-management/pages/workload-management.adoc
> +== Replica/Partition routing based on CPU Usage
This makes a lot of sense. Reordered the features in the latest commit.

2023-10-14 01:01 UTC, JosephNewmanTG commented on modules/system-management/pages/workload-management.adoc
> +== Replica/Partition routing based on CPU Usage
updated this with latest commit.

2023-10-14 01:02 UTC, JosephNewmanTG commented on modules/system-management/pages/workload-management.adoc
> +This is so that queries don’t overwhelm nodes that are already under a heavy load.
Updated this with latest commit.

2023-10-14 01:02 UTC, JosephNewmanTG commented on modules/system-management/pages/workload-management.adoc
> +NOTE: Query routing mode has two options: 0=RoundRobin and 1=CPULoadAware.
updated this with latest commit.

2023-10-14 01:02 UTC, JosephNewmanTG commented on modules/system-management/pages/workload-management.adoc
> +NOTE: Default CPU threshold is set at 50.
updated this with latest commit.

2023-10-14 01:02 UTC, JosephNewmanTG commented on modules/system-management/pages/workload-management.adoc
> +NOTE: Query routing mode has two options: 0=RoundRobin and 1=CPULoadAware.
Good point. I'll keep this in mind.

2023-10-14 01:03 UTC, JosephNewmanTG commented
All changes have been made as discussed in our meeting on 10/13.

2023-10-14 01:04 UTC, merged