[DOC-2231] feat(RBAC): add docs for query ownership privilege;
tigergraph/server-docs pull request #487
Opened 2024-07-31 22:02 UTC by jue-yuan

[DOC-2231](https://graphsql.atlassian.net/browse/DOC-2231)
Doc for RBAC: Fine-grained query privilege: New Query Privilege OWNERSHIP

2024-08-27 01:09 UTC, arun-TG-PM approved these changes

2024-08-29 13:46 UTC, victorleeTG requested changes
Clarification about OWNERSHIP rules; grammar fixes

2024-08-29 13:46 UTC, victorleeTG commented on modules/user-access/pages/fine-grained-query-privileges.adoc
> +`OWNERSHIP` is a special privilege introduced since 4.1.0. It should be granted to the user created this query automatically.
```suggestion
`OWNERSHIP` is a special privilege introduced in version 4.1.0.
It is granted automatically tp the user who creates a query.
```

2024-08-29 13:46 UTC, victorleeTG commented on modules/user-access/pages/fine-grained-query-privileges.adoc
> +At the same time, this entity can grant the query privileges to other entities, including the `OWNERSHIP` privilege. Once the `OWNERSHIP` privilege is granted to another entity, the previous owner sh
```suggestion
An entity with `OWNERSHIP` privilege (e.g., the creator) on a query can grant privileges to other entities, including the `OWNERSHIP` privilege. Once the `OWNERSHIP` privilege is granted to another entity, the previous owner loses `OWNERSHIP` privilege on this query.
[NOTE]
====
Each object can have only one explicit owner entity.  
====
```

2024-08-29 13:46 UTC, victorleeTG commented on modules/user-access/pages/fine-grained-query-privileges.adoc
> +At the same time, this entity can grant the query privileges to other entities, including the `OWNERSHIP` privilege. Once the `OWNERSHIP` privilege is granted to another entity, the previous owner sh
@jue-yuan: "Should" is the wrong word.
"Should" means "it is the right or correct way".  It also implies that the wrong or incorrect way could happen, so it introduces uncertainty.  We do not want uncertainty about whether TigerGraph implements the language rules or not.

2024-08-29 13:46 UTC, victorleeTG commented on modules/user-access/pages/fine-grained-query-privileges.adoc
> +Users with the `admin` role in one graph should hold the `OWNERSHIP` privilege on all queries in this graph implicitly.
```suggestion
Users with the `superuser` role hold the `OWNERSHIP` privilege on all queries in all graphs implicitly.

Users with the `admin` role in one graph hold the `OWNERSHIP` privilege on all queries in this graph implicitly.
```

2024-08-29 13:46 UTC, victorleeTG commented on modules/user-access/pages/fine-grained-query-privileges.adoc
> +** `OWNERSHIP` privilege can only be granted at individual query level and only be granted to one entity, e.g.: a user or a user-defined role.
```suggestion
** `OWNERSHIP` privilege can only be granted at the individual query level and only to one entity, e.g.: a user or a user-defined role.
```

2024-08-29 13:46 UTC, victorleeTG commented on modules/user-access/pages/fine-grained-query-privileges.adoc
> +.Ex. Grant `OWNERSHIP` privilege on existing queries q3 in graph `g1` to user `u1`:
```suggestion
.Ex. Grant `OWNERSHIP` privilege on existing query q3 in graph `g1` to user `u1`:
```

2024-08-29 14:00 UTC, victorleeTG commented
Cancelled because this PR proposed to merge DOC-2231 into DOC-2230.
Because DOC-2230 was already merged to the dev/staging branch, this PR is being replaced with one to merge DOC-2231 to 4.1.o.

2024-08-29 14:00 UTC, closed without merging