DOC-226 docs(crr): improve Enable the CRR setup;
tigergraph/server-docs pull request #497
Opened 2024-08-16 12:13 UTC by runlilong

2024-08-22 20:56 UTC, chengjie-qin approved these changes

2024-08-28 09:27 UTC, victorleeTG requested changes
See my comments in the DOC ticket.

2024-08-29 08:23 UTC, arun-TG-PM approved these changes

2024-10-08 02:56 UTC, runlilong commented
@victorleeTG  the pr has been updated, could you take a look?

2024-10-26 00:33 UTC, victorleeTG commented on modules/cluster-and-ha-management/pages/set-up-crr.adoc
> +If there is no proper backup, use `gadmin backup create <pr_latest_backup>` to create one. For more details refer to xref:tigergraph-server:backup-and-restore:backup-cluster.adoc[].
```suggestion
If there is no suitable backup, use `gadmin backup create <pr_latest_backup>` to create one.
For more details refer to xref:tigergraph-server:backup-and-restore:backup-cluster.adoc[].
```

2024-10-26 00:33 UTC, victorleeTG commented on modules/cluster-and-ha-management/pages/set-up-crr.adoc
> +Adding the backup tag to `gadmin backup restore <backup tag> --dr` will enable CRR in a regular restore.
```suggestion
Adding `--dr` to `gadmin backup restore <backup tag>` enables CRR in a regular restore. 
```

2024-10-26 00:33 UTC, victorleeTG commented on modules/cluster-and-ha-management/pages/set-up-crr.adoc
> +Specifically, for the switching between PR and DR, before the switch, it is necessary to xref:tigergraph-server:crr:troubleshooting.adoc#_check_data_consistency_between_primary_and_dr[Check data cons
```suggestion
Specifically, when switching between PR and DR, before the switch, it is necessary to xref:tigergraph-server:crr:troubleshooting.adoc#_check_data_consistency_between_primary_and_dr[check data consistency between primary and DR]
```

2024-10-26 00:33 UTC, victorleeTG approved these changes

2024-10-26 00:34 UTC, merged