DOC-2276 add jwt token enhancement
tigergraph/server-docs pull request #501
Opened 2024-08-29 10:04 UTC by xun-gao-tigergraph

https://graphsql.atlassian.net/browse/DOC-2276

2024-08-29 10:16 UTC, dadongwang-tg commented on modules/user-access/pages/jwt-token.adoc
> +The JWT token generated in this section is only supported by restpp side.
refactor to:
The JWT token issued by a third party is limited to authentication on the RESTPP side exclusively. To enable authentication for both GSQL and RESTPP services, it is recommended to generate the token using the GSQL API service.

2024-08-29 17:59 UTC, victorleeTG requested changes

2024-08-29 17:59 UTC, victorleeTG commented on modules/user-access/pages/jwt-token.adoc
> +The JWT token issued by a third party is limited to authenticate on the RESTPP side exclusively. To enable authentication for both GSQL and RESTPP services, it is recommended to generate the token us
```suggestion
The JWT token issued by a third party is limited to authentication for RESTPP services only.
To enable authentication for both GSQL and RESTPP services, it is recommended to generate the token using the GSQL API service.
```

2024-12-17 00:45 UTC, dadongwang-tg commented
we have supported 3rd party JWT token used in GSQL side as well in 4.2.0 and 4.1.2, ticket: GLE-8672

2024-12-17 00:45 UTC, closed without merging